import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { css } from "@emotion/react";
import styled from "@emotion/styled";
const color = "white";

const CssStylesForButton = css`
  padding: 32px;
  background-color: red;
  font-size: 24px;
  border-radius: 4px;
  &:hover {
    color: ${color};
  }
`;

const Button = styled.button`
  ${CssStylesForButton}
`;

const Div = styled.div`
  ${CssStylesForButton}
`;

const SButton = styled.button`
  padding: 32px;
  background-color: red;
  font-size: 24px;
  border-radius: 4px;
  &:hover {
    color: ${color};
  }
`;

const SDiv = styled.button`
  padding: 32px;
  background-color: red;
  font-size: 24px;
  border-radius: 4px;
  &:hover {
    color: ${color};
  }
`;

const SButtonProps = styled.button<{ colorProp: string }>`
  padding: 32px;
  background-color: red;
  font-size: 24px;
  border-radius: 4px;
  &:hover {
    color: ${({ colorProp }) => colorProp};
  }
`;

const SDivProps = styled.div<{ colorProp: string }>`
  padding: 32px;
  background-color: red;
  font-size: 24px;
  border-radius: 4px;
  &:hover {
    color: ${({ colorProp }) => colorProp};
  }
`;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Button>CSS + Styled button</Button>
          <Div>CSS + Styled div</Div>

          <SButton>Styled button</SButton>
          <SDiv>Styled div</SDiv>

          <SButtonProps colorProp="green">
            Styled button with props
          </SButtonProps>
          <SDivProps colorProp="green">Styled div with props</SDivProps>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
